replicaCount: 2
image:
  repository: ghcr.io/saimudunuri04/customer-churn-service
  tag: "52fb9e052812fa14b4aa91c1360c3853bb00ceb6"
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  port: 8000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
env: {}
envFromSecretName: ""
volumeMounts: []
volumes: []
