replicaCount: 2
image:
  repository: ghcr.io/saimudunuri04/customer-churn-service
  tag: "922dc1677d02d6570c2170514e0bdae23121d945"
  pullPolicy: IfNotPresent
imagePullSecrets: []
service:
  port: 8000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
env: {}
envFromSecretName: ""
volumeMounts: []
volumes: []
